name: Publish Culture Service Docker Image
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the nodejs-backend Docker image
        run: |
          cd culture_service && docker build . --tag ghcr.io/tomdieu/agro-help-culture-service:latest
          docker run ghcr.io/tomdieu/agro-help-culture-service:latest
          docker push ghcr.io/tomdieu/agro-help-culture-service:latest
